name: UI Tests
on: [push]
jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Allure report
        run: sudo docker-compose run my_tests /bin/sh -c "ls -la && pwd"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          publish_dir: ./allure-report
          clean: true